var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":14,"id":3457,"methods":[{"el":13,"sc":5,"sl":11}],"name":"ComboPreprocessingTechnique","sl":6}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_107":{"methods":[{"sl":11}],"name":"createComboTechniqueAndClearComboParts","pass":true,"statements":[{"sl":12}]},"test_112":{"methods":[{"sl":11}],"name":"createComboTechniqueWithDifferentNameSamePartsNoError","pass":true,"statements":[{"sl":12}]},"test_170":{"methods":[{"sl":11}],"name":"canLoadTechniqueFromTextWithFourPartsInCorrectOrder","pass":true,"statements":[{"sl":12}]},"test_298":{"methods":[{"sl":11}],"name":"createComboTechniqueFromStrings","pass":true,"statements":[{"sl":12}]},"test_314":{"methods":[{"sl":11}],"name":"everyBeanHasItsOwnInstanceOfFactorieProvider","pass":true,"statements":[{"sl":12}]},"test_356":{"methods":[{"sl":11}],"name":"canReadPropertiesFile","pass":true,"statements":[{"sl":12}]},"test_437":{"methods":[{"sl":11}],"name":"canRunMultipleDetectionOnStudentsDirs","pass":true,"statements":[{"sl":12}]},"test_441":{"methods":[{"sl":11}],"name":"runDetectionWithComboTechnique","pass":true,"statements":[{"sl":12}]},"test_478":{"methods":[{"sl":11}],"name":"ifComboTechniqueNameIsGivenToCreateToolReturnComboTechniqueIfExists","pass":true,"statements":[{"sl":12}]},"test_48":{"methods":[{"sl":11}],"name":"ifTechniqueWithSameNameOverwrite","pass":true,"statements":[{"sl":12}]},"test_496":{"methods":[{"sl":11}],"name":"ifOneTechniqueIsNotOkLoadOthersAndReportLoadFailure","pass":true,"statements":[{"sl":12}]},"test_562":{"methods":[{"sl":11}],"name":"canLoadMultipleTechniqueFromText","pass":true,"statements":[{"sl":12}]},"test_596":{"methods":[{"sl":11}],"name":"printsDetectionOutputDirs","pass":true,"statements":[{"sl":12}]},"test_625":{"methods":[{"sl":11}],"name":"loadsComboTechniquesFromFile","pass":true,"statements":[{"sl":12}]},"test_639":{"methods":[{"sl":11}],"name":"passesItselfAsPresenterToUseCase","pass":true,"statements":[{"sl":12}]},"test_69":{"methods":[{"sl":11}],"name":"callsComboTechniqueLoaderAndPresenterToLoadComboTechniquesFromFile","pass":true,"statements":[{"sl":12}]},"test_7":{"methods":[{"sl":11}],"name":"everyBeanHasItsOwnInstanceOfFactorieProvider","pass":true,"statements":[{"sl":12}]},"test_704":{"methods":[{"sl":11}],"name":"passesCorrectConfigurationToTemplateExclusionTechnique","pass":true,"statements":[{"sl":12}]},"test_716":{"methods":[{"sl":11}],"name":"canLoadTechniqueFromTextWithTwoParts","pass":true,"statements":[{"sl":12}]},"test_72":{"methods":[{"sl":11}],"name":"canLoadMultipleComboTechniquesFromFile","pass":true,"statements":[{"sl":12}]},"test_724":{"methods":[{"sl":11}],"name":"passesCorrectRequestModelToUseCase","pass":true,"statements":[{"sl":12}]},"test_738":{"methods":[{"sl":11}],"name":"passesCorrectConfigurationFileToSimilarityDetectionTool","pass":true,"statements":[{"sl":12}]},"test_751":{"methods":[{"sl":11}],"name":"tryCreateComboTechniqueWithSameNameRetrunError","pass":true,"statements":[{"sl":12}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [107, 314, 716, 7, 738, 562, 69, 437, 72, 478, 496, 751, 441, 48, 298, 724, 112, 170, 704, 625, 639, 596, 356], [107, 314, 716, 7, 738, 562, 69, 437, 72, 478, 496, 751, 441, 48, 298, 724, 112, 170, 704, 625, 639, 596, 356], [], []]
