var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":9,"id":4736,"methods":[{"el":8,"sc":5,"sl":6}],"name":"SherlockNormalisePPTechnique","sl":3}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_170":{"methods":[{"sl":6}],"name":"canLoadTechniqueFromTextWithFourPartsInCorrectOrder","pass":true,"statements":[{"sl":7}]},"test_314":{"methods":[{"sl":6}],"name":"everyBeanHasItsOwnInstanceOfFactorieProvider","pass":true,"statements":[{"sl":7}]},"test_356":{"methods":[{"sl":6}],"name":"canReadPropertiesFile","pass":true,"statements":[{"sl":7}]},"test_437":{"methods":[{"sl":6}],"name":"canRunMultipleDetectionOnStudentsDirs","pass":true,"statements":[{"sl":7}]},"test_48":{"methods":[{"sl":6}],"name":"ifTechniqueWithSameNameOverwrite","pass":true,"statements":[{"sl":7}]},"test_505":{"methods":[{"sl":6}],"name":"createsToolObjectBasedOnName","pass":true,"statements":[{"sl":7}]},"test_596":{"methods":[{"sl":6}],"name":"printsDetectionOutputDirs","pass":true,"statements":[{"sl":7}]},"test_625":{"methods":[{"sl":6}],"name":"loadsComboTechniquesFromFile","pass":true,"statements":[{"sl":7}]},"test_636":{"methods":[{"sl":6}],"name":"canRunAllToolsOnAllTehcniques","pass":true,"statements":[{"sl":7}]},"test_639":{"methods":[{"sl":6}],"name":"passesItselfAsPresenterToUseCase","pass":true,"statements":[{"sl":7}]},"test_7":{"methods":[{"sl":6}],"name":"everyBeanHasItsOwnInstanceOfFactorieProvider","pass":true,"statements":[{"sl":7}]},"test_704":{"methods":[{"sl":6}],"name":"passesCorrectConfigurationToTemplateExclusionTechnique","pass":true,"statements":[{"sl":7}]},"test_724":{"methods":[{"sl":6}],"name":"passesCorrectRequestModelToUseCase","pass":true,"statements":[{"sl":7}]},"test_738":{"methods":[{"sl":6}],"name":"passesCorrectConfigurationFileToSimilarityDetectionTool","pass":true,"statements":[{"sl":7}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [314, 7, 738, 437, 48, 505, 724, 170, 704, 625, 639, 596, 636, 356], [314, 7, 738, 437, 48, 505, 724, 170, 704, 625, 639, 596, 636, 356], [], []]
